spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mp?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      aop-patterns: com.example.demo4.*
      filters: stat,wall

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
        wall:
          enabled: true


mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/AccountMapper.xml

management:
  endpoints: #配置所有端点信息
    enabled-by-default: true #默认开启所有的端点
    web:
      exposure:
        include: '*' #以web方式暴露所有端点
  endpoint: #对某个端点的具体配置
    health:
      show-details: always
